# Generated by Django 5.2 on 2025-04-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tweet_id", models.CharField(max_length=255, unique=True)),
                ("user_id", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField()),
                ("full_text", models.TextField()),
                ("url", models.URLField()),
                ("fecha_scraping", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
