# Generated by Django 5.2 on 2025-04-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0003_tweetslist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
