# Generated by Django 5.2 on 2025-04-21 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0005_resultadoanalisissentimiento"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ResultadoAnalisisSentimiento",
        ),
    ]
